name: Java CI with Maven

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:
      # 1. Cloning
      - name: Git clone
        uses: actions/checkout@v4

      # 2. Install Java 17
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      # 3. Run tests (not stop workflow if failure )
      - name: Build and run tests with Maven
        run: mvn -B -e clean test -Dselenium.headless=true || true
        env:
          CHROME_OPTIONS: --remote-allow-origins=*;--disable-gpu;--no-sandbox;--disable-dev-shm-usage;--headless=new;--window-size=1920,1080

      # 4. Output failed tests
      - name: Print failed tests
        if: failure()
        run: |
          echo "---- TEST FAILURES ----"
          cat target/surefire-reports/*.txt || true

      # 5. Attach screenshots
      - name: Attach screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: ${{ github.workspace }}/screenshots

      # 6. Get Allure (gh-pages)
      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # 7. Build  Allure report
      - name: Build Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      # 8. Upload  Allure report artifact
      - name: Upload Allure report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report

      # 9. Check allure-results
      - name: Check Allure results
        run: ls -la target/allure-results

      # 10. Publish  Allure to GitHub Pages
      - name: Publish Allure report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Upload Allure HTML report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report